on: [push]

jobs:
  default_site:
    runs-on: ubuntu-latest
    name: Build Default Site
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quartz Build Action
        uses: ./
        with:
          source: example_projects/default/content
          page_title: "Quartz WF"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: default
          path: _site/

  complex_site:
    runs-on: ubuntu-latest
    name: Build Complex Site
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quartz Build Action
        uses: ./
        with:
          source: example_projects/custom_theme/content
          quartz_config: example_projects/custom_theme/config/quartz.config.ts
          quartz_layout: example_projects/custom_theme/config/quartz.layout.ts
          quartz_icon: example_projects/custom_theme/images/icon_mod.png
          quartz_banner: example_projects/custom_theme/images/og-image_mod.png
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: themed
          path: _site/